version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adoorei
    ports:
      - "8001:80"
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: adoorei
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"
